name: Build and Release KM271-WIFI Firmware

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  build:
    name: Build Firmware
    runs-on: ubuntu-latest
    container: ghcr.io/the78mole/platformio-docker:v1.0.0

    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Fix git ownership (for Docker container)
        run: |
          git config --global --add safe.directory /__w/KM271-WIFI-Test/KM271-WIFI-Test
          git config --global --add safe.directory ${{ github.workspace }}

      - name: Determine if this is a release
        id: release_check
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ] || [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "release=true" >> $GITHUB_OUTPUT
          else
            echo "release=false" >> $GITHUB_OUTPUT
          fi

      - name: Generate semantic version (only for release)
        if: steps.release_check.outputs.release == 'true'
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
          branch: main
          tag_prefix: "v"
          major_pattern: "/^(feat|fix|refactor)!:/"
          minor_pattern: "/^feat:/"
          search_commit_body: true
          bump_each_commit: true

      - name: Export version
        if: steps.release_check.outputs.release == 'true'
        run: |
          echo "MAJOR=$(echo '${{ steps.semver.outputs.version }}' | cut -d. -f1)" >> $GITHUB_ENV
          echo "MINOR=$(echo '${{ steps.semver.outputs.version }}' | cut -d. -f2)" >> $GITHUB_ENV
          echo "PATCH=$(echo '${{ steps.semver.outputs.version }}' | cut -d. -f3)" >> $GITHUB_ENV

      - name: Set fallback version for test builds
        if: steps.release_check.outputs.release != 'true'
        run: |
          echo "MAJOR=0" >> $GITHUB_ENV
          echo "MINOR=0" >> $GITHUB_ENV
          echo "PATCH=0" >> $GITHUB_ENV

      - name: Run PlatformIO build (all environments)
        run: |
          # Build all environments defined in platformio.ini
          # Using 'pio run' without --environment builds all environments by default
          platformio run

      - name: Create factory images
        run: |
          echo "🏭 Creating factory images with esptool..."
          
          # Use modern esptool command (without .py suffix)
          ESPTOOL_CMD="esptool"
          echo "🔧 Using esptool command: $ESPTOOL_CMD"
          
          # Create factory image for each built environment
          for dir in .pio/build/*; do
            env_name=$(basename "$dir")
            echo "🔍 Processing environment: $env_name"
            
            if [ -f "$dir/firmware.bin" ] && [ -f "$dir/bootloader.bin" ] && [ -f "$dir/partitions.bin" ]; then
              echo "✅ Found all required binaries for $env_name"
              
              # Get dynamic offsets from PlatformIO build data
              if [ -f "$dir/idedata.json" ]; then
                echo "📋 Reading offsets from $env_name/idedata.json..."
                BOOTLOADER_OFFSET=$(python3 -c "import json; data=json.load(open('$dir/idedata.json')); print(data.get('flash_images', [{}])[0].get('offset', '0x1000'))")
                # For ESP32, partitions are typically at 0x8000 and firmware at 0x10000
                PARTITIONS_OFFSET="0x8000"
                FIRMWARE_OFFSET="0x10000"
                echo "🔧 Using dynamic bootloader offset for $env_name: $BOOTLOADER_OFFSET"
              else
                echo "⚠️  idedata.json not found for $env_name, using default offsets"
                BOOTLOADER_OFFSET="0x1000"
                PARTITIONS_OFFSET="0x8000"
                FIRMWARE_OFFSET="0x10000"
              fi
              
              # Create factory image with bootloader, partitions, and firmware (using modern merge-bin)
              factory_filename="KM271-WIFI-${env_name}-factory.bin"
              $ESPTOOL_CMD --chip esp32 merge-bin -o "$factory_filename" \
                $BOOTLOADER_OFFSET "$dir/bootloader.bin" \
                $PARTITIONS_OFFSET "$dir/partitions.bin" \
                $FIRMWARE_OFFSET "$dir/firmware.bin"
              echo "✅ Factory image created for $env_name: $(ls -lh $factory_filename)"
            else
              echo "⚠️  Missing binaries for $env_name, skipping factory image"
            fi
          done

      - name: Archive firmware binaries
        if: steps.release_check.outputs.release == 'true'
        run: |
          mkdir -p dist
          echo "📦 Collecting firmware binaries from all environments..."
          
          # Collect all firmware binaries from different environments
          for dir in .pio/build/*; do
            env_name=$(basename "$dir")
            echo "🔍 Checking environment: $env_name"
            
            if [ -f "$dir/firmware.bin" ]; then
              echo "✅ Found firmware.bin for $env_name"
              cp "$dir/firmware.bin" "dist/KM271-WIFI-${env_name}-firmware-v${{ steps.semver.outputs.version }}.bin"
            fi
            
            # Also check for other common PlatformIO output files
            if [ -f "$dir/firmware.elf" ]; then
              echo "📋 Found firmware.elf for $env_name (debug symbols)"
              cp "$dir/firmware.elf" "dist/KM271-WIFI-${env_name}-firmware-v${{ steps.semver.outputs.version }}.elf"
            fi
          done
          
          # Also copy all factory images
          for factory_file in KM271-WIFI-*-factory.bin; do
            if [ -f "$factory_file" ]; then
              echo "🏭 Found factory image: $factory_file"
              cp "$factory_file" "dist/$(basename "$factory_file" .bin)-v${{ steps.semver.outputs.version }}.bin"
            fi
          done
          
          echo "📋 Final artifact list:"
          ls -la dist/

      - name: Generate Release Notes
        if: steps.release_check.outputs.release == 'true'
        id: release_notes
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');

            let latestTag = '';
            try {
              latestTag = execSync('git describe --tags --abbrev=0').toString().trim();
            } catch {
              latestTag = '';
            }

            let commitLog = '';
            if (latestTag) {
              commitLog = execSync(`git log ${latestTag}..HEAD --pretty=format:"- %s"`).toString();
            } else {
              commitLog = execSync('git log --pretty=format:"- %s"').toString();
            }

            // Zugriff auf PR-Beschreibung
            let prText = '';
            if (context.payload.pull_request) {
              prText = context.payload.pull_request.body || '';
            }

            const notes = `## KM271-WIFI Firmware Release v${{ steps.semver.outputs.version }}

            ### Hardware Revision Support
            This firmware supports Hardware Revision 0.0.6 (HW_REV=000006) as configured in platformio.ini.

            ### Changes
            ${prText ? prText + '\n\n' : ''}${commitLog}

            ### Binary Files
            - \`KM271-WIFI-esp32dev-firmware-v${{ steps.semver.outputs.version }}.bin\` - Main firmware binary
            - \`KM271-WIFI-esp32dev-factory-v${{ steps.semver.outputs.version }}.bin\` - Complete factory image
            
            Additional binaries may be available for other hardware revisions if configured.

            ### Flash Instructions
            **For firmware updates (existing device):**
            \`\`\`
            esptool --chip esp32 --port /dev/ttyUSB0 --baud 921600 write_flash 0x10000 KM271-WIFI-esp32dev-firmware-v${{ steps.semver.outputs.version }}.bin
            \`\`\`
            
            **For complete flash (new device):**
            \`\`\`
            esptool --chip esp32 --port /dev/ttyUSB0 --baud 921600 write_flash 0x0 KM271-WIFI-factory-v${{ steps.semver.outputs.version }}.bin
            \`\`\`
            `;
            core.setOutput('body', notes);

      - name: Create GitHub Release
        if: steps.release_check.outputs.release == 'true' && steps.semver.outputs.version != ''
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.semver.outputs.version }}
          name: KM271-WIFI Release v${{ steps.semver.outputs.version }}
          body: ${{ steps.release_notes.outputs.body }}
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
